# 配置服务器信息
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  # 端口
  port: 8089
spring:
  # redis设置
  redis:
    #配置redis的主机地址，需要修改成自己的
    host: 127.0.0.1
    database: 0
    # redis端口
    port: 0000
    # redis密码
    password: 000000
  # sa-token配置（基本可不作修改）
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: token-xr
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid
  #mysq1数据库相关配置
  datasource:
    # 数据库地址
    url: xxxx
    # 用户名
    username: xxxx
    # 密码
    password: xxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 120000
  resources:
    static-locations: classpath:templates/
  servlet:
    multipart:
      max-file-size: 8000MB
      max-request-size: 8000MB
logging:
  level:
    com.lazyfish.codeshare.dao: debug
userProjects:
  # 保存的资源路径
  path: I:\xxx\xxx
